// State and territory codes: https://pe.usps.com/text/pub28/pub28apb.htm
// Marine area codes: https://www.weather.gov/media/directives/010_pdfs_archived/pd01003002j.pdf
const AREA_NAMES = {
  AL: 'Alabama',
  AK: 'Alaska',
  AS: 'American Samoa',
  AR: 'Arkansas',
  AZ: 'Arizona',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District of Columbia',
  FL: 'Florida',
  GA: 'Georgia',
  GU: 'Guam',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VI: 'U.S. Virgin Islands',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming',
  MP: 'Northern Mariana Islands',
  PW: 'Palau',
  FM: 'Federated States of Micronesia',
  MH: 'Marshall Islands',
  AM: 'Western North Atlantic Ocean',
  AN: 'Northwest North Atlantic Ocean',
  GM: 'Gulf of Mexico',
  LC: 'Lake St. Clair',
  LE: 'Lake Erie',
  LH: 'Lake Huron',
  LM: 'Lake Michigan',
  LO: 'Lake Ontario',
  LS: 'Lake Superior',
  PH: 'Central Pacific Ocean',
  PK: 'North Pacific Ocean near Alaska',
  PM: 'Western Pacific Ocean',
  PS: 'South Central Pacific Ocean',
  PZ: 'Eastern North Pacific Ocean',
  SL: 'St. Lawrence River',
} as const;

export const AREA_CODES = Object.keys(AREA_NAMES);

export const formatAreaName = (code: string): string => {
  const name = Object.hasOwn(AREA_NAMES, code)
    ? AREA_NAMES[code as keyof typeof AREA_NAMES]
    : undefined;
  return name ? name + ' (' + code + ')' : code;
};
