import { useLayoutEffect, useRef, type UIEvent } from 'react';
import type { Alert } from '../lib/types';

type Props = {
  alerts: Alert[];
  viewKey: string;
  enabled: boolean;
  loadMore: () => Promise<void>;
};
type Anchor = { id: string; offset: number };

// Only a downward scroll can request a page. Short/empty lists never auto-fill.
export const useAlertScroll = ({
  alerts,
  viewKey,
  enabled,
  loadMore,
}: Props) => {
  const scrollRef = useRef<HTMLDivElement>(null);
  const previousTop = useRef(0);
  const requestPending = useRef(false);
  const anchor = useRef<Anchor | null>(null);
  const previousView = useRef(viewKey);

  const rememberPosition = (root: HTMLDivElement) => {
    const top = root.getBoundingClientRect().top;
    const visibleTop = Math.max(
      top,
      root.querySelector('thead')?.getBoundingClientRect().bottom ?? top,
    );
    const item = Array.from(
      root.querySelectorAll<HTMLElement>('[data-alert-id]'),
    ).find(element => element.getBoundingClientRect().bottom > visibleTop);
    anchor.current = item
      ? {
          id: item.dataset.alertId!,
          offset: item.getBoundingClientRect().top - top,
        }
      : null;
  };

  useLayoutEffect(() => {
    const root = scrollRef.current;
    if (!root) return;
    if (previousView.current !== viewKey) {
      previousView.current = viewKey;
      anchor.current = null;
      root.scrollTop = 0;
    } else if (anchor.current) {
      const saved = anchor.current;
      const item = Array.from(
        root.querySelectorAll<HTMLElement>('[data-alert-id]'),
      ).find(element => element.dataset.alertId === saved.id);
      if (item)
        root.scrollTop +=
          item.getBoundingClientRect().top -
          root.getBoundingClientRect().top -
          saved.offset;
      anchor.current = null;
    }
    // Ignore the scroll event generated by restoring the anchor or resetting filters.
    previousTop.current = root.scrollTop;
  }, [alerts, viewKey]);

  const onScroll = (event: UIEvent<HTMLDivElement>) => {
    const root = event.currentTarget;
    const movedDown = root.scrollTop > previousTop.current;
    previousTop.current = root.scrollTop;
    rememberPosition(root);
    if (
      !alerts.length ||
      !movedDown ||
      !enabled ||
      requestPending.current ||
      root.scrollHeight <= root.clientHeight + 1
    )
      return;
    if (root.scrollHeight - root.scrollTop - root.clientHeight > 120) return;
    rememberPosition(root);
    requestPending.current = true;
    void loadMore().finally(() => {
      requestPending.current = false;
    });
  };

  return { scrollRef, onScroll };
};
